version: "3.8"

services:
  # --- SERVICIO 2: El Cerebro (IA) ---
  ollama:
    image: ollama/ollama:latest
    container_name: pdf_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Guarda los modelos descargados para no bajarlos cada vez
    networks:
      - pdf_network # <-- FALTABA ESTO: Conecta a la IA a la red puente

  # --- SERVICIO 3: Nuestra API (El Recepcionista) ---
  api:
    build: . # Le dice que arme la imagen usando el Dockerfile que creamos recién
    container_name: pdf_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env # Le inyecta las variables de entorno
    depends_on:
      - ollama # Le avisa que espere a que Ollama arranque primero
    networks:
      - pdf_network # Se conecta a la red externa

# Declaramos los discos virtuales ("volúmenes")
volumes:
  ollama_data: # <-- BORRAMOS el mongo_data que había quedado suelto acá

# Le decimos a Docker: "No crees una red nueva, usá la que ya creó la base de datos"
networks:
  pdf_network:
    external: true
